### ISSUE TITLE
New DA: Scientific Calculator

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#211]
Take the existing Calculator DA and add trig functions.

**Comment by inexorabletash** [comment]
Inspiration: BeagleWrite's calculator DA:

![image](https://user-images.githubusercontent.com/771547/87097730-ad32e500-c1fa-11ea-9f9f-d6a4f01023df.png) ![image](https://user-images.githubusercontent.com/771547/87097751-bd4ac480-c1fa-11ea-82fb-2e409860d738.png)

**Comment by c0mmander8** [comment]
Keep the current non-scientific, simple calculator around as an alternative mode that you can switch to from the scientific calculator and vice versa though for those that would prefer to use the current non-scientific, simple calculator instead of the scientific calculator. If for some reason this is not feasible or realistic, keep the current non-scientific, simple calculator DA around as an extra bonus for those that would prefer to use it instead of the scientific calculator DA.

**Comment by c0mmander8** [comment]
The choice of whichever calculator mode is chosen should be saved, so that the next time the Calculator DA is launched, the Calculator DA can launch directly into that calculator mode.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/157934186-829324f0-29bf-4b65-bd54-5ab75efa0757.png)

* No, I am not going to give it a different name in the title bar.
* No, I am not going to implement it as a separate mode of the existing Calculator DA.
