### ISSUE TITLE
Update the included version of the MGTK to the version included with BeagleWrite 3.3 and port over the BeagleWrite 3.3 and Quark Catalyst 3.0 desk accessories

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#226]
Please update the included version of the MGTK to the version included with BeagleWrite 3.3, which is from 1989 and 3 years newer than the one included with Apple II DeskTop 1.1, and port over the BeagleWrite 3.3 desk accessories. Please keep the existing DAs too, even when they overlap, as an option for people who would prefer to use those instead. Please adopt the BeagleWrite 3.3 menu line separators, as referenced in issue #135, but keep the existing scroll arrows, as they match the early Mac and the IIGS. See JohnMBrooks comments in issue #53. Check out the list of and the screenshots of the BeagleWrite 3.3 DAs at https://vintagegeek.wordpress.com/2017/09/06/beaglewrite-for-apple-ii-prodos-8/. You can download BeagleWrite 3.3 at ftp://ftp.apple.asimov.net/pub/apple_II/images/productivity/word_processing/beagle_write/.

**Comment by c0mmander8** [comment]
Please also try and port over the Quark Catalyst 3.0 desk accessories. Although mostly duplicative of the existing DAs, some people would prefer the Quark Catalyst 3.0 DAs' look over those of the existing DAs. It should be an easier lift than porting the BeagleWrite 3.3 DAs over, since the version of MGTK Quark Catalyst 3.0 uses is from 1985 and 1 year older than the one included with Apple II DeskTop 1.1. Check out the screenshots of the Quark Catalyst 3.0 DAs at http://toastytech.com/guis/qcat.html. You can download Quark Catalyst 3.0 from https://winworldpc.com/product/quark-catalyst/30 and from https://macgui.com/downloads/?file_id=10019. There is a crack available to remove the copy protection from Quark Catalyst 3.0 at http://www.hackzapple.com/phpBB2/viewtopic.php?t=941&view=previous&sid=2a3014c6efd5866a99593df60539f7e4.

**Comment by inexorabletash** [comment]
I spent some time but can find no indication that BeagleWrite is using MouseGraphics ToolKit. Memory searches don't reveal any patterns, e.g. common code segments, GrafPort, definitions, etc. At first I thought I had found some, but it was because I launched BW from A2D and there was some memory that hadn't been overwritten yet. :( The fonts are also completely different.

I also checked out the DAs. They don't support movement. Some features are nice - the calendar one with per-date notes is neat, and the calculator has some more features but that's already tracked in a separate issue. But it does not appear any code can be re-used.

A separate to-do would be to have the Font Preview DA support the BW font format, whatever it is. (As well as HRCG and Apple /// fonts).

**Comment by c0mmander8** [comment]
What about the Quark Catalyst 3.0 desk accessories?

**Comment by c0mmander8** [comment]
What about the Quark Catalyst 3.0 desk accessories?

**Comment by inexorabletash** [comment]
You can file separate bugs for any Quark DAs you think make sense to try to replicate.

Look at existing bugs to see what such issues should look like.
