### ISSUE TITLE
Make the Shift-Apple-` and Shift-Apple-Tab keypresses cycle backwards through open windows

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#230]
Please, as referenced in issues #143 and #154, make the Shift-Apple-` and Shift-Apple-Tab keypresses cycle backwards through open windows.

**Comment by inexorabletash** [comment]
<kbd>Shift</kbd> can't be detected on all systems, so <kbd>Shift</kbd>+<kbd>Apple</kbd>+<kbd>Tab</kbd> may not be worth it. <kbd>Apple</kbd>+<kbd>~</kbd> should be pretty easy, though.

**Comment by inexorabletash** [comment]
On the IIgs, `KEYMODREG` Bit 0 should provide <kbd>Shift</kbd> key detection.

On the Platinum IIe, `BUTN2` Bit 7 would provide <kbd>Shift</kbd> key detection per (https://retrocomputing.stackexchange.com/questions/11395/what-combinations-of-modifier-keys-can-you-detect-on-an-apple-ii), but determining that model can't be done programmatically. We could grab the button state on startup (on local testing with a non-Platinum IIe, I always see it as high) as a mask.

But since this would be very inconsistent to document, I'm just going to leave it to just <kbd>Shift</kbd>+<kbd>Apple</kbd>+<kbd>`</kbd> since that is unambiguous.

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am using Apple II DeskTop on an Apple IIGS or on a Platinum Apple IIe and familiar keyboard shortcuts from other platforms involving the Shift key do not work.
**Describe the solution you'd like**
Please reopen this issue and, as referenced above and in issue #373, as an extra bonus for those users of Apple II DeskTop using an Apple IIGS, a Platinum Apple IIe or any other model that can detect the Shift key being pressed, make the Shift-Apple-Tab keypress cycle backwards through open windows in addition to the already existing Shift-Apple-` (Apple-~) keypress.

**Describe alternatives you've considered**
Keep on using the Shift-Apple-` (Apple-~) keypress to cycle backwards through open windows, just as I have always done.

**Additional context**
Despite the added inconsistent documentation, this issue is extremely handy for when I am using Apple II DeskTop on an Apple IIGS or on a Platinum Apple IIe and will be able to use the Shift-Apple-Tab keypress to cycle backwards through open windows without thinking about which keypress combination I have to use, just like I do on other platforms.

**Comment by c0mmander8** [comment]
I see that the make the Shift-Apple-` keypress cycle backwards through open windows part of this issue was fixed in commit 1c4acb2.
