### ISSUE TITLE
Port over the Quark Catalyst 3.0 desktop patterns

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#250]
Port over the Quark Catalyst 3.0 desktop patterns. When they overlap with the existing desktop patterns, keep both versions, for greater choice and customizability. You can download Quark Catalyst 3.0 from https://winworldpc.com/product/quark-catalyst/30 and from https://macgui.com/downloads/?file_id=10019. There is a crack available to remove the copy protection from Quark Catalyst 3.0 located at http://www.hackzapple.com/phpBB2/viewtopic.php?t=941&view=previous&sid=2a3014c6efd5866a99593df60539f7e4.

**Comment by inexorabletash** [comment]
Can you provide screenshots of any such patterns?

They're also easy to add to the Control Panel DA, so this might be a project for you to get started building the project yourself.

**Comment by c0mmander8** [comment]
Sorry, I cannot provide screenshots of any such patterns. However the Quark Catalyst 3.0 manual located at https://www.callapple.org/soft/ap2/quark/Quark_Catalyst_3.0.pdf and at https://winworldpc.com/product/quark-catalyst/30 shows solid-colored desktop patterns ranging from off-white to gray throughout the book and a unique small black squares on a thin white grid pattern on page 93 where it states that there are "10 different desktop background patterns" included with Quark Catalyst 3.0.

**Comment by inexorabletash** [comment]
You can grab images from here:

ftp://ftp.apple.asimov.net/pub/apple_II/images/disk_utils/quark_catalyst/

**Comment by inexorabletash** [comment]
The backgrounds aren't very exciting:

gray/checkerboard:
![image](https://user-images.githubusercontent.com/771547/88617030-83771c00-d04a-11ea-99ca-08ad966cdd8f.png)

black:
![image](https://user-images.githubusercontent.com/771547/88617041-896cfd00-d04a-11ea-878a-0c142c27c8f5.png)

white:
![image](https://user-images.githubusercontent.com/771547/88617049-8c67ed80-d04a-11ea-95b2-0378f6db300d.png)

dark gray:
![image](https://user-images.githubusercontent.com/771547/88617054-8eca4780-d04a-11ea-8e22-79e5605ea750.png)

big grid:
![image](https://user-images.githubusercontent.com/771547/88617061-912ca180-d04a-11ea-8089-19160a97d30b.png)

squares:
![image](https://user-images.githubusercontent.com/771547/88617067-94279200-d04a-11ea-825b-c2637f082bf1.png)

small grid:
![image](https://user-images.githubusercontent.com/771547/88617074-97228280-d04a-11ea-90cd-b005d202fb01.png)

stripes:
![image](https://user-images.githubusercontent.com/771547/88617080-9984dc80-d04a-11ea-9324-4f716bccce8d.png)

apples:
![image](https://user-images.githubusercontent.com/771547/88617094-9f7abd80-d04a-11ea-8a7d-ecaaab8ec4af.png)

Qs:
![image](https://user-images.githubusercontent.com/771547/88617102-a275ae00-d04a-11ea-878a-9aff2d490df2.png)

**Comment by inexorabletash** [comment]
The only ones which seem worth porting are the grids/squares, and they don't work exactly since MGTK uses an 8x8 DHR pixel grid, Catalyst is using something else. Here's an approximation of a few:

![image](https://user-images.githubusercontent.com/771547/88617411-760e6180-d04b-11ea-9c0b-6ecb40f9e500.png)
![image](https://user-images.githubusercontent.com/771547/88617447-8f171280-d04b-11ea-8a5d-4532df180a6f.png)
![image](https://user-images.githubusercontent.com/771547/88617587-de5d4300-d04b-11ea-9966-e2f33284197f.png)
![image](https://user-images.githubusercontent.com/771547/88617541-be2d8400-d04b-11ea-8343-e2bcc0bc654b.png)
![image](https://user-images.githubusercontent.com/771547/88617690-211f1b00-d04c-11ea-9679-7aba6273241f.png)

If any of those appeal to you, spin up a PR for a `desk.acc/control.panel.s` change that adds them.

**Comment by inexorabletash** [comment]
The file is running low on space, and none of the patterns are particularly compelling. Closing.

**Comment by ph0enix-c0der** [comment]
Please reopen this issue and, as referenced above, add all of the original Quark Catalyst 3.0 desktop patterns and also add all of your approximations of all of the Quark Catalyst 3.0 desktop patterns.

**Comment by inexorabletash** [comment]
Please observe the [Code of Conduct](https://github.com/a2stuff/a2d/blob/main/CODE_OF_CONDUCT.md#addendum), which explicitly calls out:

"Further examples of unacceptable behavior due to the burden on project maintainers and the noise created for other project participants:" / "Replying to closed issues asking for reconsideration, without providing additional data."

While you often have good suggestions, your disregard for social norms is increasingly tiresome.

**Comment by ph0enix-c0der** [comment]
I think that adding all of the original Quark Catalyst 3.0 desktop patterns and also adding all of your approximations of all of the Quark Catalyst 3.0 desktop patterns to the Control Panel control panel in Apple II DeskTop would be a cute, nifty addition to Apple II DeskTop.

**Comment by ph0enix-c0der** [comment]
This issue is now issue #858.

**Comment by night-0wl22** [comment]
**Is your feature request related to a problem? Please describe.**

I really like all of the Quark Catalyst 3.0 desktop patterns and think that they all should be available for all users of Apple II DeskTop to use.

**Describe the solution you'd like**

As referenced in issue #858, I think that adding all of the original Quark Catalyst 3.0 desktop patterns and also adding all of your approximations of all of the Quark Catalyst 3.0 desktop patterns to the Control Panel control panel in Apple II DeskTop would be a cute, nifty addition to Apple II DeskTop.
