### ISSUE TITLE
Make Arrow keypress select the next item in the respective direction

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#274]
Make Arrow keypress select the next item in the respective direction, just like the later Mac and the later IIGS.

**Comment by inexorabletash** [comment]
I did some exploration of this. The Apple-H mode which allows you to highlight icons works in a fascinating way. It grabs icons from the current active window and desktop volume icons, then bubble sorts them (by Y then X) into a list. The left/right arrow keys then let you navigate the list. This made more sense before I made icons variable height, since it sorts by the top of the icon, not the "baseline" of the icon. Also, it's only one dimensional - only left/right arrows do anything.

In contrast, on modern macOS Finder (for comparison), left/right/up/down all work, but it is constrained to the holder of the active selection (either a window or the desktop) it seems to be truly two dimensional using some fun heuristics. The up arrow literally select the next icon directly above the current icon. If you arrange icons in a diagonal line, you can't move between them. If you arrange icons in interesting patterns you can end up with the up arrow taking one path and the down arrow taking another path entirely.

I'm tempted to remove the Apple-H mode entirely and just have left/right cycle through next/prev icon (in file order) regardless of position, scrolling the window (if necessary) and cycling from window icons to desktop icons and back. But that's a lot of work.
