### ISSUE TITLE
Add support for opening preview file types in the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#295]
As referenced in issue #293, add support for opening preview file types in the Apple menu, just like the later Mac.

**Comment by inexorabletash** [comment]
I'm pondering. 

The reason it doesn't work is that the Preview DAs look at the current selection to see what to open. If you put a picture in `DESK.ACC`, select a different picture, then pick the Apple menu item the selected picture will get shown because the Preview DA does get launched but shows the selection.

Fixing this would be a good thing, actually: instead of groveling around inside the window code for the selected icons, the path could be passed to the DA. But... then the trick of moving `SHOW.TEXT.FILE` to `DESK.ACC` to be able to preview arbitrary types would no longer work.

**Comment by I3arana** [comment]
Trying to get my head around what you are both getting at, are you implying you give the preview apps a file selector dialog to open what the user wants instead of the modeless icon highlight method?

**Comment by inexorabletash** [comment]
The Preview DAs currently determine what file to open by asking DeskTop what file is selected and in which window. 

This precludes directly invoking a file to preview by path, because there would be no selection.

**Comment by I3arana** [comment]
Yes thats current, so what is being proposed?

**Comment by inexorabletash** [comment]
What I'm pondering is having DeskTop provide a path directly, so the Preview DA doesn't depend on selection. That would simplify the Preview DA logic (no need to call into DeskTop to ask about selection) and allow the feature requested in this issue. 

It would preclude Preview DAs from being used in the Apple menu as regular DAs, since they would no longer know to ask for the selection. 

I'm still pondering.

**Comment by c0mmander8** [comment]
Can you make it so both features work-that you can add support for opening preview file types in the Apple menu and also keep the ability of Preview DAs to look at the current selection to see what to open and be used in the Apple menu as regular DAs?

**Comment by c0mmander8** [comment]
I do not want you to take away any existing features.
