### ISSUE TITLE
Make changes to the Apple menu take effect immediately

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#301]
Make changes to the Apple menu resulting from changes to the Desk.Acc folder, including adding and removing items from the Desk.Acc folder and sorting the Desk.Acc folder with the Sort Directory DA, take effect immediately instead of having to quit and relaunch Apple II DeskTop for them to take effect, just like the later Mac.

**Comment by inexorabletash** [comment]
Nope

**Comment by c0mmander8** [comment]
Why?

**Comment by c0mmander8** [comment]
Why? Changes to the Selector menu and changes to the Selector dialog box take effect immediately. Why not here too?

**Comment by I3arana** [comment]
Possibly because It takes alot of time for such a small return.
   If I may also add, commander8, you may not be aware of it, But observing these few short weeks, well, it is social courtesy when making many small requests to add please and thankyou to the requestee as a bare minimum. I have little doubt that Inexorable is doing this out of a passion and free time project.I say this because I think I am picking up on a sense of frustration of at least a lack of courtesy in your requests and at most a Demand rather than a polite contribution.
  I tell you this so you dont burn any bridges on this project, or worse still burn out our star contributor, who I think does an insane job of pushing out useful changes several times a week (thanks mate)
