### ISSUE TITLE
GSplus crashes when launching Disk Copy

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#306]
GSplus v0.14 (the lastest version of the program) crashes when launching Disk Copy from Apple II DeskTop on Windows.

**Comment by I3arana** [comment]
Is that a emulator problem or something else? does gsport or kegs do the same thing? do 8 bit emulators also crash doing the same?
 This id your Job as a bugtester to acertain this and report on it. Does it crash on a real machine? what alpha version were you using at the time? all info you need to file in a bug report.

**Comment by c0mmander8** [comment]
I always use the latest (pre-)alpha of Apple II DeskTop 1.2 in my issues and comments, in this case Apple II DeskTop 1.2 (Pre-)Alpha 22.

**Comment by I3arana** [comment]
Ok, you need to specify this each time you file a report among other important things.

**Comment by inexorabletash** [comment]
Thanks for the report. Repros back to pre-alpha 20 at least. Likely repros in A2D 1.1 / MouseDesk 2.0 but those bomb out on GSplus due to tickling an unsupported softswitch.

The emulator dies during drive enumeration, which likely means it's making a bad call into drive firmware directly or via a SmartPort call. This is an emulator bug, but we shouldn't be doing that.

The disk copy code makes bad assumptions about device driver addresses. It filters out anything in Slot 3 (RAM disks), but assumes that the driver address is in the form $CnXX and pokes around at offsets from $Cn00. On GSplus this is bogus - the address for remapped smartport devices is at $FCE6. (The non-remapped drivers are at slot 5 = $C50A, slot 6 (Disk II) = $D000, and slot 7 = $C70A, which is all good.) Virtual II - which is where I do most of my testing - doesn't support more than two devices per slot so this doesn't manifest.

I fixed up most of the places in DeskTop that do bad things with device driver addresses, but [per the release notes](https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md#known-issues) I haven't touched Disk Copy at all. So... I guess there's a project.

**Comment by inexorabletash** [comment]
The linked revision prevents the crash and in theory makes Disk Copy behave properly with remapped drives, but I haven't thoroughly tested Disk Copy at all. There are likely other bugs lurking.
