### ISSUE TITLE
Should the window title in the title bar be prefixed with the folder glyphs?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#320]
Should the window title in the title bar be prefixed with the folder glyphs, just like folders in the Apple menu?

**Comment by c0mmander8** [comment]
Should the window title in the title bar of a folder, not a volume, be prefixed with the folder glyphs, just like folders in the Apple menu?

**Comment by inexorabletash** [comment]
Please stop repeating yourself in comments, although I appreciate the clarification of restricting this suggestion to subdirectories. 

It's an interesting suggestion, but I think this would add little benefit, and be visual clutter.  I added the glyphs to the Apple menu because I found it surprising when an item opened up a window rather than a DA, even as the implementer. I don't see the same justification applying here - distinguishing top-level from subdirectories seems less important.
