### ISSUE TITLE
Allow Shift-clicking to select multiple contiguous and/or noncontiguous icons

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#340]
Allow Shift-clicking to select multiple contiguous and/or noncontiguous icons, just like the Mac and the IIGS.

**Comment by c0mmander8** [comment]
If Shift-clicking will not work on some Apple II models due to the Apple II's limitations, allow Apple-clicking in addition to Shift-clicking to compensate.

**Comment by c0mmander8** [comment]
If Shift-clicking will not work on some Apple II models due to the Apple II's limitations, allow Apple-clicking in addition to Shift-clicking in order to compensate.

**Comment by c0mmander8** [comment]
It seems like Open-Apple already works. Make Solid-Apple work too and Shift for the models that support it.

**Comment by I3arana** [comment]
The solid apple key is a different key to open apple. the solid apple key is used for a handful of things only.This is misuse and has no place. See apple's interface guideline documents.

**Comment by c0mmander8** [comment]
The theme throughout Apple II DeskTop is that you can use Solid-Apple for almost anything Open-Apple can do.

**Comment by I3arana** [comment]
Inconsistant with apples other gui products and one of those cases is where you bullied project lead into adding it.

**Comment by inexorabletash** [comment]
Let's try and be polite, please.

**Comment by inexorabletash** [comment]
@c0mmander8 is correct that DeskTop does use Solid-Apple and Open-Apple interchangeably in most cases. While I agree with @I3arana that this is not consistent with much Apple GUI software, I find it convenient! With the Virtual II emulator since by default the Open-Apple key is mapped to <kbd>⌘ command</kbd> and reserved for the app. So I use <kbd>⌥ option</kbd> as the modifier key.

<kbd>Shift</kbd>-clicking can't be detected on 8-bit Apples, but I agree that it's frustrating that Solid-Apple doesn't work for extending selections - I very frequently make this mistake!

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am using Apple II DeskTop on an Apple IIGS or on a Platinum Apple IIe and familiar keyboard actions from other platforms involving the Shift key do not work.

**Describe the solution you'd like**
Please reopen this issue and, as referenced above and in issue #373, as an extra bonus for those users of Apple II DeskTop using an Apple IIGS, a Platinum Apple IIe or any other model that can detect the Shift key being pressed, allow Shift-clicking to select multiple contiguous and / or noncontiguous icons in addition to the already existing Apple-clicking, just like the Mac and the IIGS.
**Describe alternatives you've considered**
Keep on Apple-clicking to select multiple contiguous and / or noncontiguous icons, just as I have always done.

**Additional context**
Despite the added inconsistent documentation, this issue is extremely handy for when I am using Apple II DeskTop on an Apple IIGS or on a Platinum Apple IIe and will be able to Shift-click to select multiple contiguous and / or noncontiguous icons without thinking about which key I have to hold down, just like I do on other platforms.

**Comment by inexorabletash** [comment]
In general, I'm not interested in adding any IIgs-specific logic. IIgs users have a perfectly good Finder to use!

I briefly looked into shift key detection on the Platinum IIe though, since the "shift key mod" is supported in Virtual ][. Unfortunately, it turns out to be problematic. With the mod (or on the Platinum IIe), if the shift key is _down_ then PB2 ($C063) has high bit _clear_. If the shift key is _up_, the high bit is _set_.

This means that on a machine without the shift-key "mod", looking at PB2 will appear to show that the shift key is always down! Since you can't programmatically detect the presence of the "mod", this can't be a feature that would work without a setting somewhere, and that's getting too niche to support when there's a clear alternative (the Apple keys).

Sorry about that - if the sense of PB2 was reversed, this would be really easy. The documentation on the shift-key mod is sparse; the author of a different emulator was surprised to learn the details and had it implemented backwards in their emulator!

**Comment by inexorabletash** [comment]
Hah, okay, shower thoughts: just snapshot PB2 on startup (and assume <kbd>shift</kbd> is not being held down) and compare against the snapshot. Works like a charm.

Since this is not restricted to the IIgs, and it's not significant additional logic, I've added support for <kbd>shift</kbd> for extending selections. I am not planning to make <kbd>shift</kbd>+<kbd>apple</kbd> a distinct modifier from just <kbd>apple</kbd> anywhere, though. I also probably won't document this, since explaining the support matrix would be wordy.

**Comment by c0mmander8** [comment]
As referenced in issue #230 and issue #373, what about the Shift-Apple-Tab keypress cycling backwards through open windows in addition to the Shift-Apple-` keypress though?

**Comment by inexorabletash** [comment]
As I wrote above:

> I am not planning to make <kbd>shift</kbd>+<kbd>apple</kbd> a distinct modifier from just <kbd>apple</kbd> anywhere, though.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit cba366d and in commit 68835d6.

**Comment by c0mmander8** [comment]
As referenced in commit 68835d6, please switch the order of these lines in a2d/res/notes/testplan.txt for greater consistency in the text in the document:

"* IIgs: Launch Desktop. Select two volume icons. Hold Shift and click on the desktop, not on an icon. Verify that selection is not cleared.
* Platinum IIe: Launch Desktop. Select two volume icons. Hold Shift and click on the desktop, not on an icon. Verify that selection is not cleared." should be 

"* Platinum IIe: Launch Desktop. Select two volume icons. Hold Shift and click on the desktop, not on an icon. Verify that selection is not cleared.
* IIgs: Launch Desktop. Select two volume icons. Hold Shift and click on the desktop, not on an icon. Verify that selection is not cleared." instead for greater consistency in the text in the document.

**Comment by c0mmander8** [comment]
As referenced in commit 68835d6, please add these additional lines to a2d/res/notes/testplan.txt for greater consistency in the text in the document:

"* Launch Desktop. Open a volume containing files. Click on a file icon. Hold Open-Apple and click a different file icon. Verify that selection is extended.
* Launch Desktop. Open a volume containing files. Click on a file icon. Hold Solid-Apple and click a different file icon. Verify that selection is extended.
* Launch Desktop. Open a volume containing files. Select two file icons. Hold Open-Apple and click on the window, not on an icon. Verify that selection is not cleared.
* Launch Desktop. Open a volume containing files. Select two file icons. Hold Solid-Apple and click on the window, not on an icon. Verify that selection is not cleared." should be 

"* Launch Desktop. Open a volume containing files. Click on a file icon. Hold Open-Apple and click a different file icon. Verify that selection is extended.
* Launch Desktop. Open a volume containing files. Click on a file icon. Hold Solid-Apple and click a different file icon. Verify that selection is extended.
* Platinum IIe: Launch Desktop. Open a volume containing files. Click on a file icon. Hold Shift and click a different file icon. Verify that selection is extended.
* IIgs: Launch Desktop. Open a volume containing files. Click on a file icon. Hold Shift and click a different file icon. Verify that selection is extended.
* Launch Desktop. Open a volume containing files. Select two file icons. Hold Open-Apple and click on the window, not on an icon. Verify that selection is not cleared.
* Launch Desktop. Open a volume containing files. Select two file icons. Hold Solid-Apple and click on the window, not on an icon. Verify that selection is not cleared.
* Platinum IIe: Launch Desktop. Open a volume containing files. Select two file icons. Hold Shift and click on the window, not on an icon. Verify that selection is not cleared.
* IIgs: Launch Desktop. Open a volume containing files. Select two file icons. Hold Shift and click on the window, not on an icon. Verify that selection is not cleared." instead for greater consistency in the text in the document.
