### ISSUE TITLE
The startup disk located at s7d1 does not appear on the desktop when launching Apple II DeskTop by quitting the Selector after booting the Selector directly at startup on GSplus

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#344]
The startup disk located at s7d1 does not appear on the desktop when launching Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program) by quitting the Selector after booting the Selector directly at startup on GSplus 0.14 (the latest version of the program). If I have it mounted, only the ancillary hard drive located at s7d2 appears on the desktop. S7d1 also does not appear in Special > Format a Disk... and in Special > Erase a Disk.... Instead, a mysterious s0d1 Disk II appears there. Also, the Disk Copy Quick Copy dialog box appears garbled and does not work in this scenario. I also cannot switch from the Disk Copy Quick Copy dialog box to the Disk Copy Disk Copy dialog box. If I have the ancillary hard drive mounted, Change Drive in File > Copy a File..., in File > Delete a File..., in Selector > Add an Entry... and in Selector > Edit an Entry... makes Apple II Desktop crash. If I do not have the ancillary hard drive mounted, File > Copy a File..., File > Delete a File..., Selector > Add an Entry... and Selector > Edit an Entry... simply crash without me doing anything further.

**Comment by I3arana** [comment]
Good bug hunting! Can you replicate that bug in another emulator?

**Comment by inexorabletash** [comment]
Please use the templates to file issues and follow the recommended structure, providing reproduction steps in lists rather than giant paragraphs of run-on sentences. 

If you cannot follow this guidance you will be permanently banned from this repository.

I really appreciate your excitement about the project and your attention to detail, so I hope you can adjust your behavior and communication.
