### ISSUE TITLE
Improve performance of open-folder-and-close-current-window action

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#351]
As referenced in issue #9, allow tunneling folders instantly and directly, without first opening the child folder, then going back to the parent folder and closing the parent folder and finally then going back to the child folder, just like the later Mac and the later IIGS.

**Comment by c0mmander8** [comment]
Why not?

**Comment by inexorabletash** [comment]
Because...

This is my hobby project. I work on it as a meditative challenge, like assembling a jigsaw puzzle (which is what I spent the morning doing). It is intellectually stimulating but without demands like a real job. I'm not accountable to anyone, I can prioritize my work as I see fit, and I can choose to tackle particular issues or not as I see fit. Unlike my day job, I don't have to look at schedules, or manage the work or careers of others. It is public because I want to share the results with others, and I do value constructive, useful feedback; I'd also like to see meaningful contributions by others.

When I review the open issues and see repeated posts that disregard my repeated requests to follow templates for reporting issues, I become frustrated. When I'm frustrated, working on it is no longer fun. If I am not having fun, I will stop working on the project.

It is apparent that you have a different communication style than others. I urge you to look at how issues are reported against other projects on github and adopt these conventions for issue reporting. And I ask you again to follow the issue templates when reporting issues. They exist to make it easier for others to understand the issue. If you refuse to follow the template structure as has been repeatedly requested of you, I feel no obligation to spend the time to explain my response.

I hope the above makes sense. I expect you and others who visit this repo to make an effort to respond to feedback about communication. If there are other ways I can help set expectations, such as clarifying the issue templates, providing more detailed code of conduct or contributor guidelines, chatting live, etc. then please let me know.

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it takes so long for Apple II DeskTop to redraw windows when tunneling folders.

**Describe the solution you'd like**
Please reopen this issue and, as referenced above and in issue #9, allow tunneling folders instantly and directly, without first opening the child folder, then going back to the parent folder and closing the parent folder and finally then going back to the child folder, just like the later Mac and the later IIGS.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
This should be more feasible now that there's internal support for opening via a path.

**Comment by inexorabletash** [comment]
The remaining complexity here is that you can multi-select icons and issue an open command. Currently, the new windows are opened by iterating over the icons. If the logic is changed to close the active window before opening, the filenames of the icons would need to be saved somewhere to construct the paths to open. 65 bytes for the window path + 8*16 bytes for the names, so it's probably doable, but tedious to code up.

**Comment by inexorabletash** [comment]
Given the recent performance improvements above, I'm going to close this issue out. In the distant future, this could be tackled at the MGTK level.

**Comment by ph0enix-c0der** [comment]
This issue should be added to the Apple II DeskTop 1.2 milestone.
