### ISSUE TITLE
The file selection of multiple icons is garbled after opening and then closing a folder

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#364]
**Describe the bug**
The file selection of multiple icons is garbled after opening and then closing a folder.
**To Reproduce**
1. Start the Apple II DeskTop located on the A2DeskTop_800k.2mg included with Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
2. Double-click on and open A2.Desktop.
3. Go to the File menu and select File > Select All.
4. Double-click on and open Preview.
5. Close Preview.
6.The file selection of all icons is garbled.

**Expected behavior**
The file selection of multiple icons is the same as it was before opening the folder or the file selection of multiple icons is cleared instead.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Fun! Things definitely get garbled after opening with multiple selection. It wasn't too hard to this, followed by a lockup:

![image](https://user-images.githubusercontent.com/771547/103466495-975e3280-4cfa-11eb-866f-6d49b62c0be1.png)

**Comment by c0mmander8** [comment]
This issue might be related to issue #218. I do not know though.

**Comment by c0mmander8** [comment]
I take back my last comment. My last comment was meant for issue #374.

**Comment by inexorabletash** [comment]
Thanks for a clear bug report. I've tracked down what's going on, but I'll have to think for a while more about how to fix it given the limitations of MGTK.

Here's what happens:
* When the window for the "Preview" folder is opened, selection is not cleared. I was incorrect in an earlier comment that only the active window can have selection. Selection is retained in the original window (or desktop) until it is cleared by setting selection elsewhere, changing view, etc.
* When a window is closing, DeskTop clears selection and (if possible) sets selection to the "parent" icon of the closing window (i.e. the "Preview" folder). The window is destroyed, it animates the window frame shrinking, and repaints windows using MGTK's "update event" logic.

There are several contributing problems here:

* If selection is not in the active window and selection is cleared, the icons are not repainted. This is because MGTK doesn't support drawing to anything but the top-most window except in update events. (MGTK is not as clever as QuickDraw on the Mac/IIgs and doesn't support arbitrary clipping regions.) That means at the start of the "window close" operation, when selection is cleared, the parent window does have selection cleared but the icons still show as highlighted.
* When a window is destroyed, the underlying windows are redrawn through MGTK "update events"; to minimize overdraw, MGTK sets up a clipping rect for just where the old window used to be, and lets DeskTop redraw windows back to front but only in the clipping rect. This means that the parent window does get to redraw its now un-selected icons without a highlight... but only where the closed window was.

With different repro steps you can experiment with these limitations and get some other fun glitches.

So... how to fix?

* Rewriting MGTK to be as powerful as QuickDraw is off the table. (More concretely: it's a lovely idea, but a project I will not be taking on in my lifetime.)
* After certain operations like a selection clearing, a full redraw of all windows could be forced. This would be correct, but pretty slow.
* The specific repro steps for this bug might be a common case: where selection is present in the window that will become top-most after the close. Repainting the top-most window entirely is doable, so we could put in a hack that conditionally fully repaints the top-most window's contents. It would not be a comprehensive solution, though.

**Comment by inexorabletash** [comment]
This implements the hack:

```diff
diff --git a/desktop/main.s b/desktop/main.s
index a9da3ef..8c79ffe 100644
--- a/desktop/main.s
+++ b/desktop/main.s
@@ -4594,6 +4594,8 @@ deltay: .word   0
 
         jsr     LoadActiveWindowIconTable
 
+        copy    selected_window_id, old_selected_window_id
+
         jsr     clear_selection
 
         ldx     active_window_id
@@ -4672,9 +4674,24 @@ no_icon:
         jsr     check_item
         jsr     update_window_menu_items
 
-        ;; BUG: This doesn't ensure the window containing selection redraws
-        ;; fully. https://github.com/a2stuff/a2d/issues/364
-        jmp     clear_updates_and_redraw_desktop_icons
+        jsr     clear_updates_and_redraw_desktop_icons
+
+        ;; If selection was cleared out of the new top-most window, force
+        ;; a full redraw. https://github.com/a2stuff/a2d/issues/364
+        lda     active_window_id
+        beq     :+
+        cmp     old_selected_window_id
+        bne     :+
+
+        jsr     LoadActiveWindowIconTable
+        jsr     set_port_from_window_id
+        jsr     draw_window_entries
+        jsr     LoadDesktopIconTable
+
+:       rts
+
+old_selected_window_id:
+        .byte   0
 .endproc
```
