### ISSUE TITLE
Running Sort Directory from Selector > Run an Entry... freezes DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#413]
**Describe the bug**
Attempting to run Sort Directory from Selector > Run an Entry... freezes Apple II DeskTop.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Selector menu and go to Selector > Add an Entry....
3. Add Sort Directory to the Selector.
4. Click OK.
5. Click on the Selector menu and go to Selector > Run an Entry....
6. Click on Sort Directory.
7. Click OK.
8. An error dialog box stating "The syntax of the pathname is invalid." appears.
9. Click OK.
10. Apple II DeskTop freezes.

**Expected behavior**
Attempting to run Sort Directory from Selector > Run an Entry... should not freeze Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 26 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Nice find.

The DA executes before the "Run an Entry..." window is closed, so the DA can't find the path of the active window. Then things go off the rails.

If Eyes or another DA is tried instead, the underlying dialog window can't be redrawn, but this isn't catastrophic.

There are probably two bugs:

* The Sort Directory DA should be more robust and not cause DeskTop to freeze in this case.
* The "Run an Entry..." should be closed before the execution occurs. This was probably fine before DAs, etc, were supported since the app would just exit.
