### ISSUE TITLE
Separate Mouse Graphics Tool Kit for application use

### ISSUE THREAD

**Issue by eschaton** [a2stuff/a2d#451]
It would be awesome if the Mouse Graphics Tool Kit implementation used by Apple II Desktop was just a library that was used by Apple II Desktop and that could be used by not just desk accessories but applications loaded from it without additional loading/relocation/etc. In essence, it could be an “SDK” for Apple II Desktop, useful in developing other graphical Apple II applications.

**Comment by eric-ja** [comment]
I started this some years ago, but haven't worked on it since. I split 
up the code into different source files based on logical area, and added 
compilation targets for the various builds that MGTK existed in the 
wild, including the Pascal version, which was a loadable library (driver).

https://github.com/eric-ja/a2d/tree/master/mgtk


Chris Hanson wrote:

**Comment by inexorabletash** [comment]
Hey @eschaton !

Re: _"applications loaded from it without additional loading/relocation/etc"_

In practice, requiring each app (e.g. Selector, DeskTop) to include MGTK isn't a really big deal, and it avoids placing constraints on the apps. The library is BIG; loaded at $4000 it spans through $8600 or so. That's too big to place in e.g. the Aux language card area, for example, so it's going to sit in either Main or Aux main bank. If Aux then you can't use /RAM. If Main, you're very limited in where ProDOS can operate. So apps need to make decisions about where to load it depending on what other memory they're going to need.

You could imagine a convention for a collection of apps that keep it in the same place in memory, but those don't exist yet so it's premature to architect DeskTop around it. 

Having DeskTop based on an evolving MGTK would be awesome (if @eric-ja had infinite cycles!), of course. But that's a separate project, so I'm going to close this issue. For now any other app can copy MGTK out of this repo, and we can always consider making it a separate repo and including it as a subrepo here if there is real demand.

(I should note I've added a few more calls into MGTK since the 1.0F that Apple distributed. I still want to see the Oval operations in #83 added, although they're probably too big to keep in the core library.)
