### ISSUE TITLE
All of the settings contained in "DESKTOP.CONFIG" are not loaded into memory either in Disk Copy or in the Selector

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#454]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that all of the settings contained in "DESKTOP.CONFIG" are not loaded into memory either in Disk Copy or in the Selector.

**Describe the solution you'd like**
As referenced in issue #452, commit 6d95ab4, all of the settings contained in "DESKTOP.CONFIG" should be loaded into memory both in Disk Copy and in the Selector.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
This is a completely bogus issue for several reasons:

* At the time when this issue was filed it was incorrect. Selector has loaded the config file since 85fadcf971d595c65c732b3085d2a9c6790493d5 (April 2020 - about a year). Disk Copy has loaded the config file since 6d95ab4 *as noted in the issue itself*. Not valid.
* This issue describes a perception about the code (as noted above as incorrect), not behavior of the program when tested. If you notice a flaw when inspecting the code, please verify it by testing. In this case, it's not a flaw of either the code (at the time reported) or the behavior (unless you are knowingly filing a duplicate issue about a released version). Either way, not valid. 
* Finally _"I'm always frustrated that..."_ is poor wording for an issue you could not possibly have been conscious of for more than a few hours. Perhaps "always" and "frustrated" don't mean what you think they mean?

I appreciate your attention to detail in reporting actual bugs, but please stop wasting my time and yours filing issues like this.
