### ISSUE TITLE
Don't close windows when the directory or an ancestor is renamed

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#469]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that a folder window or a volume window and any open subfolder windows are closed when the folder or the volume is renamed instead of the folder window's title bar or the volume window's title bar being updated with the folder's new title or the volume's new title.

**Describe the solution you'd like**
A folder window or a volume window and any open subfolder windows should not be closed when the folder or the volume is renamed. Instead, the folder window's title bar or the volume window's title bar should be updated with the folder's new title or the volume's new title, just like the Mac and the IIGS.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
Okay, more details:

* Rename, like Get Info, actually works with multiple items selected. So the logic will need to be in `do_rename`. This will render cleanup logic in `cmd_rename` obsolete, which is good as it's busted anyway if there are multiple items selected and you cancel halfway through. We could change the command to only be enabled when one non-trash item is selected, but `do_rename` is probably a better place anyway since it has the old/new paths handy.
* I just landed a change which corrects existing code which updates the icon's name right in `do_rename`. The icon is then promptly destroyed and recreated by code in `cmd_rename`, but we may be able to fix that.
* The following cases exist:
   * Volumes
       * [ ] Update all affected window paths, in `window_path_table` 
       * [ ] Update the window title if there's an open window for the volume. (via `window_title_addr_table`, indirectly) 
   * Folders
       * [ ] Update all affected window paths, in `window_path_table` 
       * [ ] Update the window title if there's an open window for the volume. (via `window_title_addr_table`, indirectly)
   * Other files:
       * [ ] SYS files change icons depending on whether or not they have a `.SYSTEM` suffix.

I don't think there are any cases that would require closing windows.

* Window title updates could be done with a full repaint at worst. Probably the best thing would be a way to invalidate a window's title area; MGTK doesn't have an "invalidate rectangle" but it really should.
* SYS files could be handled by setting a flag and forcing a window reload. Actually swapping in an icon without it moving would be tricky. We could also punt on that case.
