### ISSUE TITLE
The view field of the Copy a File... dialog box blanks out while copying a certain file or a certain folder

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#487]
**Describe the bug**
The view field of the Copy a File... dialog box blanks out while copying a certain file or a certain folder.

**To Reproduce**
1. Start Apple II DeskTop while booted from "A2.Desktop", which is the "A2DeskTop-1.2-alpha31-en_800k.2mg" disk image,
2. Click on the File menu and go to File > Copy a File....
3. Select "Read.Me" from the root directory of the startup disk "A2.Desktop".
4. Click OK.
5. The view field of the Copy a File... dialog box blanks out.

**Expected behavior**
The view field of the Copy a File... dialog box should not blank out while copying a certain file or a certain folder.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 31 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The view field blanks out only when copying certain files or certain folders in the Copy a File... dialog box. The view field does not blank out when copying other files or other folders in the Copy a File... dialog box.

**Comment by c0mmander8** [comment]
The folders located in the root directory of the startup disk "A2.Desktop" should still be available to select to potentially copy "Read.Me" to instead of being blanked out with the files.

**Comment by c0mmander8** [comment]
For example, the view field does not blank out when copying "Basic.System" from the root directory of the startup disk "A2.Desktop", which is the "A2DeskTop-1.2-alpha31-en_800k.2mg" disk image,

**Comment by inexorabletash** [comment]
I can't repro exactly, but something weird is going on. When I follow the repro steps, I see this:

![image](https://user-images.githubusercontent.com/771547/123350899-cc607a80-d510-11eb-9d28-ddc59d83afd9.png)

Then if I hit Cancel then OK again I see this:

![image](https://user-images.githubusercontent.com/771547/123350920-da160000-d510-11eb-95e5-8b3ffc6f1475.png)

Note that one of the folders has disappeared! Hopefully this is the same root cause...

**Comment by inexorabletash** [comment]
Here's a more informative repro:

1. Open Copy a File...
2. Go to a directory with more than 9 files, and at least N directories (with N > 0)
3. Scroll down so that the first file is not seen
4. Pick a file, doesn't matter which one
5. Click OK

Observe that N-1 folders are showing.

I think in the `update_scrollbar2` proc the clip rect is not reset if the scrollbar is deactivated.
