### ISSUE TITLE
Should the "K in disk" string in the volume info header be centered directly under the window title string like it is in Classic Mac OS System versions 0.85-7.6.1 or should the "K in disk" string in the volume info header remain the way it is currently?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#524]
Should the "K in disk" string in the volume info header be centered directly under the window title string like it is in Classic Mac OS System versions 0.85-7.6.1 or should the "K in disk" string in the volume info header remain the way it is currently?

**Comment by inexorabletash** [comment]
The current logic is to pre-compute the width of placeholder strings like " 00,000K in disk" and use that width regardless of the actual string width. Therefore it will not be perfectly centered. 

Improvements here do not seem worthwhile.

**Comment by c0mmander8** [comment]
You are misunderstanding my question. Currently, the "00,000K in disk" volume info header string is centered directly between the "000 Items" volume info header string and the "00,000K available" volume info header string. I am asking whether the "00,000K in disk" volume info header string should instead be centered directly under the window title like it is in Classic Mac OS System versions 0.85-7.6.1 instead of the way it currently is? There is a difference and there can be a big difference between the two different kinds of centering. Please look at some screenshots of Finder windows of folders and volumes in Classic Mac OS System versions 0.85-7.6.1 on the Internet to better understand my question.

**Comment by c0mmander8** [comment]
Please reopen this issue.

**Comment by inexorabletash** [comment]
Ah, thank you for explaining. I understand the difference you mean now.

This arises from the window header appearing entirely above the vertical scrollbar:

![image](https://user-images.githubusercontent.com/771547/127684651-dc064932-f1da-4484-ad8f-993fca4a54f1.png)

Whereas in DeskTop the header appears within the content area, because MGTK (the windowing/graphics library) doesn't have a notion of a header like Classic macOS does:

![image](https://user-images.githubusercontent.com/771547/127684928-ddba1087-0233-4107-b119-8c7c89b2bf72.png)

So the "in disk" is centered within the header in both cases, it's just that the header is offset. Without changing the header, it wouldn't be centered but crowded to the right. Moving the header would require a substantial rewrite of MGTK, and isn't worth the effort.
