### ISSUE TITLE
There is an inconsistent maximum number of icons

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#537]
**Describe the bug**
There is an inconsistent maximum number of icons, either 125 icons or 126 icons, in Apple II DeskTop that is less than 127 icons.

**To Reproduce**
1. Start Apple II DeskTop with just the startup disk mounted at s7d1, and no other volumes, RAMCards or RAM disks mounted.
2. Open a window of the root directory of the startup disk.
3. Click on the File menu and go to File > New Folder....
4. Name the folder "A".
5. Click OK.
6. Open the window of the folder "A" you have just created.
7. Click on the File menu and go to File > New Folder....
8. Name the folder "B".
9. Click OK.
10. Open the window of the folder "B" you have just created.
11. Move or copy files and folders or create new folders until the contents of "B" totals 115 items.
12. Close all windows except "A" and "B".
13. Create new folders until the contents of "B" totals 122 items.
14 The icon of "B" located in "A", the icons of the 122 items located in "B", the icon of the startup disk located on the desktop and the icon of the Trash can located on the desktop equals 125 icons being used by Apple II DeskTop.
15. Click on the File menu and go to File > New Folder....
16. Give the new folder a name.
17. Click OK.
18. A dialog box appears stating, "Warning! A window must be closed before opening this new catalog.".
19. Click OK.
20. The window "B" closes automatically.
21. Click on the File menu and go to File > Delete a File....
22. Select the folder you just created in steps 15-17.
23. Click OK.
24. A dialog box appears stating, "Click OK to delete: 1 file".
25. Click OK.
26. Open the window of the folder "B".
27. Close the window "A".
28. Create new folders until the contents of "B" totals 124 items.
29. The icons of the 124 items located in "B", the icon of the startup disk located on the desktop and the icon of the Trash can located on the desktop equals 126 icons being used by Apple II DeskTop.
30. Click on the File menu and go to File > New Folder....
31. Give the new folder a name.
32. Click OK.
33. A dialog box appears stating, "Warning! A window must be closed before opening this new catalog.".

**Expected behavior**
There should be a consistent maximum number of 127 icons in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 34 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
Mounting the Apple IIGS Control Panel RAM5 RAM disk and / or a volume at s7d2 each further reduce the maximum number of icons by 1 icon each.

**Comment by c0mmander8** [comment]
The screen painting error is now being tracked as issue #539.

**Comment by inexorabletash** [comment]
Root cause is that the "how many icons would be free if all volumes had an icon" logic is flawed if there are no file icons allocated.

At step 17, the calculations are:
* Total icons: 3 (disk in S7D1, Trash, A)
* Files in folder being opened: 123
* DEVCNT entries: 4 (S7D1, S6D1, S6D2, S5D1, S5D2) (it's always one less)
* free_start = $D021, free_end = $E000 (c/o one file record for A - $20 bytes + 1 for dir)
So: 123 + 3 = 126 <= 127, so that's okay
The free_record_count is (free_end - free_start) / 32 = 126 (that's right: 127 - 1)
So then free_record_count - DEVCNT = 123
And 123 (files) > 122 (slots) so this fails, as expected.

At step 28, the calculations are:
* Total icons: 2 (disk in S7D1, Trash)
* Files in folder being opened: 124
* DEVCNT entries: 4 (S7D1, S6D1, S6D2, S5D1, S5D2)
* free_start = $D000, free_end = $E000 (c/o zero file records)
So: 124 + 2 = 126 <= 127, so that's okay (same as before)
The free_record_count is (free_end - free_start) / 32 = 128 (which is wrong, should max at 127!)
So then free_record_count - DEVCNT = 124
And 124 (files) > 122 (slots) so this succeeds!

**Comment by inexorabletash** [comment]
Fixed. Per the commit comment:

> (1) Calculation for "how many file records are free?" was off by one if there were no file records, since the dir counts will always consume some bytes too. Given that max # windows is < size of file record, always one record is wasted. So max is 127, which equals kMaxIconCount.

That's what caused the inconsistency you were seeing. But also:

> (2) DEVCNT was used to reserve icons for devices, but (a) DEVCNT is one less than the number of devices and (a) it doesn't include Trash, which takes an icon.
> Fixing this will reduce the number of icons available for files, but ensures the right number of icons are reserved for devices.

In your hardware setup, you'll find that you hit the limit at 121 files at step 17, or 122 files in step 28

At step 17, the new calculations are:

Total icons: 3 (disk in S7D1, Trash, A)
Files in folder being opened: 121
DEVCNT entries: 4 (S7D1, S6D1, S6D2, S5D1, S5D2) (it's always one less)
free_start = $D021, free_end = $E000 (c/o one file record for A - $20 bytes + 1 for dir)
So: 121 + 3 = 124 <= 127, so that's okay
The free_record_count is (free_end - free_start - 1) / 32 = 126 (that's right: 127 - 1)
So then free_record_count - (DEVCNT + 2) = 126 - (4 + 2) = 120
And 121 (files) > 120 (slots) so this fails (but would succeed at 120 files)

At step 28:

Total icons: 2 (disk in S7D1, Trash)
Files in folder being opened: 122
DEVCNT entries: 4 (S7D1, S6D1, S6D2, S5D1, S5D2) (it's always one less)
free_start = $D000, free_end = $E000 (no file records)
So: 122 + 2 = 124 <= 127, so that's okay
The free_record_count is (free_end - free_start - 1) / 32 = 127 (that's right)
So then free_record_count - (DEVCNT + 2) = 127 - (4 + 2) = 121
And 122 (files) > 121 (slots) so this fails (but would succeed at 121 files)

**Comment by inexorabletash** [comment]
To find out the number of devices from within DeskTop, you can use Special > Erase a Disk. You'll see 5 devices in your configuration (so DEVCNT would be 4, if you want to run through the above math)
