### ISSUE TITLE
Screen painting error when window closed due to icon count exceeded

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#539]
A screen painting error occurs after step 18 in issue #537 if the window "A" is expanded to maximum size before step 14 in issue #537.

**Comment by inexorabletash** [comment]
I'm not seeing exactly the problem you report. As always, screenshots are appreciated, and you should spend time learning how to create screenshots as it would increase the value of your bug reports. Here's a similar repro which may be the same thing:

1. Create the maximum number of files you can have in a folder so that you can open the parent volume and the folder itself. This will vary based on the number of devices you have and their contents. In my case I have 9 devices and 9+Trash=10 and I want to leave one free for the parent so I run this:
```basic
 10  PRINT  CHR$ (4)"CREATE /RAM/F"
 20  FOR I = 1 TO 127 - 11
 30  PRINT  CHR$ (4)"SAVE /RAM/F/F"I
 40  NEXT
```
2. Start DeskTop, open the volume, and open the folder.
3. Switch to the volume window
4. File > New Folder, specify a name, OK

![image](https://user-images.githubusercontent.com/771547/129455106-8785682c-2245-4168-88cc-b4cdcb20f600.png)

**Comment by c0mmander8** [comment]
Please try again. Try expanding the window "A" to the maximum size and let the window "A" cover the desktop icons before step 14 in issue #537. A screen painting error occurs after step 18 in issue #537 in this scenario.
