### ISSUE TITLE
Apple II DeskTop opens a folder opened by double-clicking on it with the preview handler selected from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box instead of doing nothing

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#543]
**Describe the bug**
Apple II DeskTop opens a folder opened by double-clicking on it with the preview handler selected from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box instead of doing nothing.

**To Reproduce**
1. Start Apple II DeskTop while not running Apple II DeskTop from a RAMCard.
2. Add the Show Font File, the Show Image File and the Show Text File preview handlers to the Selector menu run list.
3. Open a folder by double-clicking on it.
4. Select the Show Font File, the Show Image File or the Show Text File preview handler from the Selector menu or the Selector > Run an Entry... dialog box.
5. Apple II DeskTop opens the folder opened in step 3 with the selected preview handler instead of doing nothing.
6. If the Show Font File preview handler was chosen in step 5, GSplus crashes and the emulator window is involuntarily closed.
7. If the Show Text File preview handler was chosen in step 5, Apple II DeskTop freezes.

**Expected behavior**
Apple II DeskTop should do nothing instead of open a folder opened by double-clicking on it with the preview handler selected from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 34 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I think that this issue and issue #17 share the same root cause.

**Comment by inexorabletash** [comment]
This was an interesting one, actually a combination of several issues:

(1) when you double-click on a folder (step 3) the folder actually stays selected in the background window, but the logic for passing the path the DA assumed the active window, so the path was incorrect.
(2) the Preview DAs didn't have error detection, e.g. for the file failing to open, so they'd just show whatever garbage data was sitting around in memory. That can lead to bad things (e.g. step 6)
(3) but even if the above two things are corrected, you can still preview a different file type. That's intentional - you moved the DA to the menu specifically to override the safety net. But still... better not to crash if we can help it. For text files and image files, you see garbage but it's fine. For font files, you'd hit memory corruption. So I added a little bit of file validation to ensure only somewhat valid files get previewed.
