### ISSUE TITLE
Wrong traslation in Electric Duet player

### ISSUE THREAD

**Issue by DocDoom99** [a2stuff/a2d#582]
Being a less barbaric language than English or French down here in Italy we distinguishes between "giocare" a game or with a toy and "suonare" a musical instrument or improperly a record, even the door bell.
So it should be "suonando" or more properly since it is recorded music "riproducendo"

Marco

**Comment by inexorabletash** [comment]
Thank you! As you can tell I was relying on Google Translate rather than a native speaker as I did for most of the translations. Oops.

How are these strings?

Riproducendo:
Electric Duet di Paul Lutus
Riproducendo di Alexander Patalenski   <- I'm pretty sure this one is wrong.
Premi un tasto qualsiasi per fermarti

**Comment by DocDoom99** [comment]
I (almost) never use an automatic translator, all the mistakes I make are generated by my old wetware but at least I'm not mistaken in logic!
Riproducendo:
Electric Duet di Paul Lutus
Player di Alexander Patalenski <- this is a component of the system, I think we can avoid translating
Premi un tasto qualsiasi per fermare <- fermarti is stop yourself, fermare is the infinitive form, fermare la riproduzione is too long, is a matter of personal preference you can use also ...per uscire (to go out)

Marco
