### ISSUE TITLE
Add an "Eject Disk" button to all of the file picker dialog boxes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#600]
For greater user convenience, add an "Eject Disk" button to all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, just like in the "Open...", "Save" and "Save As..." dialog boxes in Classic Mac OS System 0.85 - Mac OS 8.1.

**Comment by inexorabletash** [comment]
For reference, here's Mac OS System 6's dialog: 

![image](https://user-images.githubusercontent.com/771547/145321061-b16c68ac-4b78-4d0b-858a-7b8829cbfe50.png)

I think the challenges here are:

* Fitting the button into the dialog design
* Adding eject code (a SmartPort call) into the overlay
* Making the "enumerate the drives" logic able to be called once the dialog is already showing
* Introducing polling, to detect when a new disk is inserted.
* Making sure that disk changes when the dialog is showing are communicated back to DeskTop itself, since it will need to tear down windows/destroy icons/create icons.

I think the latter point makes this fairly infeasible without a total rewrite, but keeping this open for now.

**Comment by c0mmander8** [comment]
A Control-E keypress should be the keyboard shortcut for the proposed new "Eject Disk" button.

**Comment by inexorabletash** [comment]
Given how crowded the dialog is, and because manual eject is always possible with Apple II drives, I'm going to close this out.
