### ISSUE TITLE
Allow the user to press either the Open Apple key, the Solid Apple key or the space bar to click while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#650]
**Is your feature request related to a problem? Please describe.**
Clicking while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories is currently done by pressing the Solid Apple key, which is handily located next to the Arrow keys on the keyboards of the original Apple IIe and the original Apple IIc. But the Solid Apple key is labeled Option and is located on the opposite side of the keyboard away from the Arrow keys on the keyboards of the Apple IIGS, the Platinum Apple IIe and the Apple IIc Plus. Most functions in Apple II DeskTop, Disk Copy, the Selector and the desk accessories that can be done by pressing the Solid Apple key can also be done by pressing the Open Apple key. Plus in issue #185, you handily mentioned pressing the space bar to click, which seems easier to remember and more convenient to use than pressing either the Open Apple key or the Solid Apple key.

**Describe the solution you'd like**
As referenced in issue #185, allow the user to press either the Open Apple key, the Solid Apple key or the space bar to click while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories. Also, as referenced in issue #185, allow the user to hold either the Open Apple key, the Solid Apple key or the space bar while pressing the Arrow keys to click-and-drag while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Describe alternatives you've considered**
Just keep on pressing the Solid Apple key to click while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories. Also, just keep on holding the Solid Apple key while pressing the Arrow keys to click-and-drag while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Additional context**
As referenced in issue #185, allow the user to press either the Open Apple key, the Solid Apple key or the space bar to click while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories. Also, as referenced in issue #185, allow the user to hold either the Open Apple key, the Solid Apple key or the space bar while pressing the Arrow keys to click-and-drag while in Mouse Keys mode in Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Comment by c0mmander8** [comment]
This feature request is also for greater user interface consistency.

**Comment by inexorabletash** [comment]
In general, further enhancements to Mouse keys mode aren't worth the risk (any change can introduce unexpected behavior), code size (we're actively trying to free up space), or time, since this is a very niche feature.

Specifically here, using a regular key like Space wouldn't work well as there would be no way to drag since on the Apple you can only detect which key was pressed, or that _any_ key was released, not when a specific key was released. This is why an Apple key (which maps to a paddle button) is used.

And if the Open Apple could be used, then OA+Click couldn't be supported.

So overall: this isn't an obvious improvement, is risky and has side effects, and isn't worth more time to consider given that the feature is rarely used.
