### ISSUE TITLE
Open folder windows representing deleted folders are left on the screen after those folders are deleted

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#654]
**Describe the bug**
Open folder windows representing deleted folders are left on the screen after those folders are deleted.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image.
2. Double-click and open the "A2.Desktop" volume icon so it becomes the "A2.Desktop" volume window.
3. Click on the File menu and go File > New Folder....
4. Type "A" in the "Enter the folder name:" text field.
5. Click OK.
6. Double-click and open the "A" folder icon so it becomes the "A" folder window.
7. Click on the File menu and go File > New Folder....
8. Type "B" in the "Enter the folder name:" text field.
9. Click OK.
10. Double-click and open the "B" folder icon so it becomes the "B" folder window.
11. Click on the "A2.Desktop" volume window.
12. Drag the "A" folder icon to the Trash.
13. The "Delete..." dialog box appears stating, "Click OK to empty the trash of : 2 files".
14. Click OK.
15. The "A" folder window and the "B" folder window still exist and are still open.
16. Click on the "B" folder window.
17. Click on the "A" folder window.
18. Double-click on the "B" folder icon.
19. The "B" folder window is selected.
20. The "A" folder window and the "B" folder window still exist and are still open.

**Expected behavior**
Open folder windows representing deleted folders should be removed from the screen when those folders are deleted.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Another nice find!

Simpler repro:

1. Launch DeskTop
2. Open a volume
2. Use **File > New Folder...** to create a folder
3. Open the folder window
4. Delete the folder, either by dragging to the Trash or using **File > Delete a File...**

Fixing the drop-on-trash case is going to be somewhat irritating, as closing can't happen during the enumeration of selected icons (can only close topmost window, can't switch windows without impacting selection) and the file details are lost after the icons are gone. The **File > Delete a File...** case is more straightforward, as the path is available once the dialog closes and there's only ever one path.

One approach would be to use `FindWindowsForPrefix` as each deletion happens, and build up a table of affected windows (since there are at most 8).

Another would be to simply probe each window path after the delete and close any windows that are no longer backed by files. That's probably the easiest.
