### ISSUE TITLE
The changes you made in issue #468, commit f3dba83 and issue #658, commit ff2d615 should also be applied to the device order seen in Disk Copy and in the Selector app

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#663]
You mentioned in issue #468, commit f3dba83, referring to the changes made in that commit, that "This doesn't affect the device order seen in Disk Copy or Selector". As referenced in issue #468, commit f3dba83 and issue #658, commit ff2d615, the changes you made in issue #468, commit f3dba83 and issue #658, commit ff2d615 should also be applied to the device order seen in Disk Copy and in the Selector app. This issue is for greater user interface consistency throughout the Apple II DeskTop app, Disk Copy and the Selector app.

**Comment by c0mmander8** [comment]
As referenced in this issue, commit f501dd8, you just stated in this issue, commit f501dd8 that, "Still not planning to touch Disk Copy, since that tends to skip RAMDisks anyway." The Apple IIGS Control Panel RAM5 RAM disk is shown in Disk Copy at slot 5, drive 2 though. So, please reopen this issue and please implement this issue for Disk Copy too.

**Comment by inexorabletash** [comment]
Ah, Disk Copy filters out Slot 3 devices for some reason. Not sure why.

Anyway: No, this doesn't need to apply to Disk Copy. 
* On the DeskTop, putting the startup device in the upper right makes it more visually consistent. I like having a HD icon there.
* In File Pickers, having a physical (not RAM) drive as the default makes more sense, since it's more likely to be the correct drive for the operations you perform with the file picker, and picking another drive requires more knowledge about the dialog (i.e. that you need to click Change Drive).
* But for Disk Copy, you are presented with a list of devices, and there's not really a default. You must pick something to proceed, and picking any of the choices is approximately equal difficulty.

So I don't think it's more correct or helpful to adjust the order for Disk Copy, so  I'm going to leave it alone.
