### ISSUE TITLE
Detect all of the archive types supported by AUTO UnShrinkIt

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#669]
According to the AUTO UnShrinkIt release notes located at https://www.apple.asimov.net/images/disk_utils/Auto.UnShrink.SHK.txt, AUTO UnShrinkIt supports opening and extracting the following types of archives:

AUTO is capable of extracting the following types of archives:

NuFX (ShrinkIt)
NuFX (ShrinkIt) inside a Binary II envelope.
NuFX (ShrinkIt) inside MacBinary.
NuFX (ShrinkIt) from America-Online.
Binary II
Binary II inside a Binary II envelope.
Binary II inside MacBinary.
ACU
ACU inside a Binary II envelope.
ACU inside MacBinary.
SQ

NuFX from America-Online has a 32-byte header in front of the actual archive data if the archive was uploaded to America-Online from a Macintosh.

Please add the archive icon to all of the archive types supported by AUTO UnShrinkIt, which are listed above, and please add support for opening and extracting by double-clicking or using the File > Open command to all of the archive types supported by AUTO UnShrinkIt, which are listed above. Please identify all of the archive types supported by AUTO UnShrinkIt, which are listed above, by type-based and aux type-based type matching and also by suffix-based type matching.

**Comment by inexorabletash** [comment]
Thank you for doing the research here. This "just works" if you rename the file with a suffix `.BNY` or `.SHK` or `.BXY`

If you have a real disk image containing files that you can't open this way, please attach it. Otherwise this is only a theoretical need, so it's not worth the byte cost. I was unable to find actual usage of the ACU or SQ types anywhere, whereas I've actually run across SHK files without correct typing.

I'll leave this open for a week for examples to come in, then close it.

**Comment by inexorabletash** [comment]
Time has passed with no examples. Happy to revisit if an example can be attached that's demonstrating a real need.
