### ISSUE TITLE
Add another keyboard shortcut in addition to the already existing Shift-Tab keypress keyboard shortcut to select the previous icon sorted by name in lexicographical order in the main Apple II DeskTop app

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#671]
Add another keyboard shortcut, perhaps Open Apple-Solid Apple-Tab keypress keyboard shortcut?, in addition to the already existing Shift-Tab keypress keyboard shortcut added in issue #275, commit 9a65ebe to select the previous icon sorted by name in lexicographical order in the main Apple II DeskTop app for non-Apple IIGS, non-Platinum Apple IIe users of Apple IIs and Apple II clones that have not had the Shift key mod installed.

**Comment by inexorabletash** [comment]
Since <kbd>Apple</kbd>+<kbd>\`</kbd> acts as an alias for <kbd>Apple</kbd>+<kbd>Tab</kbd> and <kbd>Apple</kbd>+<kbd>\~</kbd> acts as an alias for <kbd>Apple</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd>, what do you think about making <kbd>\`</kbd> and <kbd>\~</kbd> work like <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd>? They're not valid filename characters so it's not a concern.

**Comment by c0mmander8** [comment]
Your counterproposal makes sense. Please implement whatever keyboard shortcuts you think are most appropriate for this situation.
