### ISSUE TITLE
Allow hitting 'ESC' to cancel a file drag operation

### ISSUE THREAD

**Issue by frankmilliron** [a2stuff/a2d#719]
Modern macOS allows users to hit Escape to cancel a file drag operation while the mouse is down. In A2D, you have to drag the items back into the original folder instead to cancel, once selected files have been moved out of the original folder.

**Comment by inexorabletash** [comment]
This is tricky - MGTK doesn't check for keyboard events while the mouse is down:

https://github.com/a2stuff/a2d/blob/5845045e091d348c1da53244a1be19f67587cf15/mgtk/mgtk.s#L5228

If that were to change, then the fix would be in toolkits/icontk.s circa https://github.com/a2stuff/a2d/blob/5845045e091d348c1da53244a1be19f67587cf15/toolkits/icontk.s#L847

* call `XdrawOutline` (same as today)
* if `highlight_icon_id` is non-zero, call `UnhighlightIcon` (same as today, but don't jump away yet...)
* `GetEvent` (so it's consumed)
* If `event_kind` is `EventKind::key_down`, then set `highlight_icon_id` to 0 (to cancel) and exit via `L9C63`
* otherwise, if `highlight_icon_id` is non-zero, exit via `L9C63` (same as today)
* otherwise, same logic as currently

**Comment by inexorabletash** [comment]
As a workaround, you can drop the files on an empty spot on the desktop.

**Comment by inexorabletash** [comment]
Just bypass MGTK. Not too bad.
