### ISSUE TITLE
Bank switching mechanisim and controller DA

### ISSUE THREAD

**Issue by I3arana** [a2stuff/a2d#739]
Ram up to 8mb (8bit) and 13/14 mb on (16 bit) systems is reletively cheap and available,
 not being needed for more than beagleapps and Appleworks . A virtually free and unused resource if utilised wisely can be harnessed and put to use in a frugal way without the need of complete rewrite of current gui's and apps, which in 2023 is just not gunna happen.
 I propose using an existing or contemporary bankswitcher, in 'desktop'? with control by DA to switch back and forth between programs without the need to exit, reload reopen files etc. 
implementing this in such a way as to be seperate, updateable or even replaceable as more powerful techniques are written without obsoleting any new gui apps written to conform to a 'closed box' .
 This overall techinque does not require  a redesign of desktop's structure or implimenting of multitasking new memory structures and the whole 9 yards.
 
one possibility is MDJ's theoretical 500byte bankswitching routine...  
 There are ofcourse existing bankswitchers for 8 bit which may be able to be utilised in this. not unlike the insertable prodos drivers such as the nsc in a directory and such with prodos 2.4.2 .

**Comment by inexorabletash** [comment]
I'm not familiar with MDJ's routine. Do you have pointers to it?

The one I know about is SoftSwitch - manual:  https://mirrors.apple2.org.za/ftp.apple.asimov.net/documentation/applications/misc/Softswitch.pdf - which includes DeskTop in its examples. Have you tried that one?

Given how most 8-bit apps completely take over the machine, I've come to appreciate DeskTop's approach of having app copied to RAMDisk on boot/use - this feature isn't obvious, but it's really cool. Instead of assuming you can switch out from underneath an app, you just make restarting really really fast.

I won't close this out, but it's unlikely something I'd pursue unless it is easy to hook into an existing switcher mechanism that handles apps like DeskTop that consume nearly all available memory on a 128k machine.

**Comment by I3arana** [comment]
Thanks mate! this stuff is hot! youve got me digging.
 Unfortunately it requires 16 bit, but my main current machine is a Rom0 GS with a2d perfect...
 BUT, are you ready for this? because youre about to leave your slippers smoking in your livingroom!
 have a close read of this, and see if you can see what I do!
 this is one way to expand A2d!!!!!!!!!!

 https://groups.google.com/g/comp.sys.apple2/c/pXOHy4EYg-M


Die then Soar.
________________________________

**Comment by inexorabletash** [comment]
Just to reduce clutter, I'm going to close this out - I think it's out of scope for A2D.
