### ISSUE TITLE
Replace thin apple glyph in menu bar with a fatter, more realistic Apple logo

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#788]
I bet the black apple icon that appears in the menu bar is a font glyph, which is why it's so thin, but this is a request to replace it with a fatter, more Apple-looking icon that resembles the Mac one of the era. That would look great.

**Comment by inexorabletash** [comment]
Yes, it's from the font. There's no non-annoying way to make it wider:
* Replacing it with a bitmap (instead of a glyph) isn't possible (without extraordinary work)
* Making it two glyphs (as is done for e.g. the folder in the menu, etc) would consume yet another character, and would be inconsistent with the single character that can be used within menus for the shortcut
* Making the font wider so it could be a single glyph would double the size of the font from 1.2k to 2.4k and maybe slow down all rendering

So... I don't think this is urgent or easy. I'm going to close it out but if anyone wants to pick it up and experiment with it (e.g. with larger font) I'm open to it.
