### ISSUE TITLE
horizontal scroll viewable area is too large in file type view

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#792]
The horizontal scrollbar in the file Type view only goes away if the window is resized to show a lot of whitespace padding to the right of the date/time.

In the first screen shot, the horizontal scrollbar is present even when it shouldn't be:

![Screenshot 2024-04-13 (22:14:59)](https://github.com/a2stuff/a2d/assets/5048913/9b8f796b-c473-4564-b246-b9fa5db39b04)

But resize the window just one more pixel wider and it disappears:

![Screenshot 2024-04-13 (22:15:11)](https://github.com/a2stuff/a2d/assets/5048913/cd4c1553-4461-47af-92aa-c02b941c4d5f)

This tells me that the horizontal scroll viewable area is too large.

**Comment by inexorabletash** [comment]
The sizing is based on the maximum possible date string length rather computing the actual width. So if you had files from September it would look correct. 

I'll take a look to see how hard it would be to make it precise, but it's probably not worth the effort.

**Comment by inexorabletash** [comment]
Ah but if it calculates correctly when you resize then there's just a missing call somewhere...

**Comment by inexorabletash** [comment]
Okay... I was right, the list view size is fixed - rather than calculating the actual date widths a fixed value is used. There was a glitch where the calculation wasn't quite right.

That said, this does mean that short dates (e.g. "April 1, 2024 at 1:11 PM") leave a lot of space to the right. It looks better with longer dates (e.g. "September 30, 2024 at 2:34 PM") 

MacOS System 6 and prior doesn't enable the horizontal scrollbar for list views! System 7 seems to have a fixed width as well. Given that... I'm going to close this out but if someone wants to take a stab at really fixing and it's not too much code or performance hit, I can advise.
