### ISSUE TITLE
Suggestion: reduce the vertical spacing of fonts in menu and item spacers

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#794]
Would it be possible to make the spacing of the menu items and menu item dividers have less vertical whitespace?

I'm comparing a2d to Catalyst:

![a2d menu](https://github.com/a2stuff/a2d/assets/5048913/95a060cb-2204-4868-af58-cd2c715977a8)

![Catalyst menu](https://github.com/a2stuff/a2d/assets/5048913/96f30b96-7177-49e1-a1f8-a50398e06037)

It seems more readable to my eyes in the Catalyst version in the menu. The items are not so spread out. 

Also, I imagine if there were less drawn whitespace, it would draw/erase faster.

**Comment by inexorabletash** [comment]
Current:
![image](https://github.com/a2stuff/a2d/assets/771547/8159c1dd-0fcb-49b1-8a66-b2cb7f27611b)

It's possible to squeeze one pixel out of each menu item height. This reduces the space before each item, and ends up with the highlighting looking bottom-heavy, due to descenders:
![image](https://github.com/a2stuff/a2d/assets/771547/66e4786a-6931-43d6-80e5-eeb6f30a7098)

Tweaking the highlight rect a bit gives this, which I think is acceptable:
![image](https://github.com/a2stuff/a2d/assets/771547/e1ca8cfa-a3f7-4c4e-b3e8-015b09590b27)

Based on the way MGTK calculates and draws menus, making the spacers smaller than regular items would be significant work, so that's not gonna happen.

**Comment by xandark** [comment]
I like the new tighter look of the menu items.
